name: flutter_shape_editor
description: An online editor for editing various Flutter shapes and morph between them.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  morphable_shape: ^0.0.6

  length_unit: ^0.0.1

  flutter_markdown: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/Icon-512.png
    - assets/images/Icon-192.png

