name: morphable_shape
description: A Flutter package for creating various shapes that are responsive and can morph betweem each other.
version: 1.6.6
repository: https://github.com/KevinVan720/morphable_shape

environment:
  sdk: ">=2.13.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_class_parser: ^0.2.5
  dimension: ^0.1.7
  animated_box_decoration: 0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

